ProductPlatform/ProductPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from ProductPlatform.script.change_order_status import start_thread_check_order_status
from orders.views import MainView

start_thread_check_order_status()  # запуск скрипта проверки заказов на актуальность по дате

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProductPlatform/orders/urls.py
from django.contrib import admin
from django.urls import path
from .views import Category, CreateOrder, OrderView, table_order, DeleteCategory, categories, DeleteOrder,UpdateOrder, DeleteResponse, UpdateResponse

app_name = 'orders'

urlpatterns = [
    path('categories/', categories, name='categories'),
    path('category/<int:id>', Category.as_view(), name='category'),
    path('create_order/', CreateOrder.as_view(), name='create_order'),
    path('view_order/<int:pk>/', OrderView.as_view(), name='view_order'),
    path("table_order/", table_order, name="table_order"),
    path('category/delete/<int:pk>/', DeleteCategory.as_view(), name='delete_category'),
    path('order_delete/<int:pk>/', DeleteOrder.as_view(), name='delete_order'),
    path('update/<int:pk>/', UpdateOrder.as_view(), name='update_order'),
    path('response_delete/<int:pk>/',
         DeleteResponse.as_view(), name='delete_response'),
    path('response_update/<int:pk>/',
         UpdateResponse.as_view(), name='response_update'),
    path('order_confirmation/<int:response_pk>/<int:order_pk>/', OrderView.order_confirmation,
         name='order_confirmation'),
    path('order_rejection/<int:response_pk>/<int:order_pk>/',
         OrderView.order_rejection, name='order_rejection'),
    


]

ProductPlatform/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import LoginListView, RegisterListView, Logout, PersonalActiveOrdersView, PersonalHistoryOrdersView, \
    ProfilePasswordResetView, ProfilePasswordResetDoneView, ProfilePasswordResetCompleteView, \
    ProfilePasswordResetConfirmView

from users.views import PersonalAccountListView, PersonalAccountEditView, ProfileView

app_name = 'users'

urlpatterns = [
    path('account/', PersonalAccountListView.as_view(), name='account'),
    path('account_edit/', PersonalAccountEditView.as_view(), name='account_edit'),
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('account_history_orders/', PersonalHistoryOrdersView.as_view(), name='account_history_orders'),
    path('account_history_orders/<int:page>/', PersonalHistoryOrdersView.as_view(), name='history_orders_page'),
    path('account_active_orders/', PersonalActiveOrdersView.as_view(), name='account_active_orders'),
    path('password-reset/', ProfilePasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', ProfilePasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ProfilePasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', ProfilePasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
]

ProductPlatform/templates/includes/button_create_order.html
<a class="create-order-btn" href="{% url 'orders:create_order' %}">+</a>

ProductPlatform/templates/includes/inc_footer.html
<div class="footer">
    <p>© 2022 HORECA_MALL</p>
</div>

ProductPlatform/templates/includes/inc_menu.html
<!-- ***** Header Area Start ***** -->
{% load static %}
<header class="header-area header-sticky background-header margin-sub-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="{% url 'main' %}" class="logo">
                        <img src="{% static 'assets/images/logo.png' %}"
                                                             alt="">
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="/">Главная</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'orders:categories' %}">Категории</a></li>
                            {% if not user.role == 'Customer' %}
                                <li><a href="{% url 'orders:table_order' %}">Доска заказов</a></li>
                            {% endif %}
                            <li><a href="{% url 'users:account_edit' %}">Личный кабинет</a></li>
                            <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'users:login' %}">Войти</a></li>
                        {% endif %}
                        {% if user.is_staff or user.is_admin %}
                            <li><a href="/admin/">Администрация</a></li>
                        {% endif %}
                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>

ProductPlatform/templates/includes/inc_sub_header.html
<!-- Sub Header -->
<div class="sub-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-sm-8">
                <div class="left-content">
                    <p>Платформа для связи <em>общепита</em> и <em>поставщиков</em>.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-4">
                <div class="right-icons">
                    <ul>
                        <li><a href="#"><i class="fa fa-whatsapp"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-vk"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

ProductPlatform/templates/includes/pagination.html
<div class="pagination col-lg-12">
    <ul>
        {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}">
                    <i class="fa fa-angle-left"></i>
                </a>
            </li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><a href="?page={{ i }}">{{ i }}</a></li>
            {% elif i < page_obj.number and i|add:'2' >= page_obj.number %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% elif i > page_obj.number and i|add:'-2' <= page_obj.number %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}">
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        {% endif %}
    </ul>
</div>