ProductPlatform/ProductPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from ProductPlatform.script.change_order_status import start_thread_check_order_status
from orders.views import MainView

start_thread_check_order_status()  # запуск скрипта проверки заказов на актуальность по дате

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProductPlatform/orders/urls.py
from django.contrib import admin
from django.urls import path
from .views import Category, CreateOrder, OrderView, table_order, DeleteCategory, categories, DeleteOrder,UpdateOrder, DeleteResponse, UpdateResponse

app_name = 'orders'

urlpatterns = [
    path('categories/', categories, name='categories'),
    path('category/<int:id>', Category.as_view(), name='category'),
    path('create_order/', CreateOrder.as_view(), name='create_order'),
    path('view_order/<int:pk>/', OrderView.as_view(), name='view_order'),
    path("table_order/", table_order, name="table_order"),
    path('category/delete/<int:pk>/', DeleteCategory.as_view(), name='delete_category'),
    path('order_delete/<int:pk>/', DeleteOrder.as_view(), name='delete_order'),
    path('update/<int:pk>/', UpdateOrder.as_view(), name='update_order'),
    path('response_delete/<int:pk>/',
         DeleteResponse.as_view(), name='delete_response'),
    path('response_update/<int:pk>/',
         UpdateResponse.as_view(), name='response_update'),
    path('order_confirmation/<int:response_pk>/<int:order_pk>/', OrderView.order_confirmation,
         name='order_confirmation'),
    path('order_rejection/<int:response_pk>/<int:order_pk>/',
         OrderView.order_rejection, name='order_rejection'),
    


]

ProductPlatform/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import LoginListView, RegisterListView, Logout, PersonalActiveOrdersView, PersonalHistoryOrdersView, \
    ProfilePasswordResetView, ProfilePasswordResetDoneView, ProfilePasswordResetCompleteView, \
    ProfilePasswordResetConfirmView

from users.views import PersonalAccountListView, PersonalAccountEditView, ProfileView

app_name = 'users'

urlpatterns = [
    path('account/', PersonalAccountListView.as_view(), name='account'),
    path('account_edit/', PersonalAccountEditView.as_view(), name='account_edit'),
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('account_history_orders/', PersonalHistoryOrdersView.as_view(), name='account_history_orders'),
    path('account_history_orders/<int:page>/', PersonalHistoryOrdersView.as_view(), name='history_orders_page'),
    path('account_active_orders/', PersonalActiveOrdersView.as_view(), name='account_active_orders'),
    path('password-reset/', ProfilePasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', ProfilePasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ProfilePasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', ProfilePasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
]

ProductPlatform/orders/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from users.models import Profile


class CategoryOrder(models.Model):
    '''Категории заказов'''
    name = models.CharField(max_length=64, unique=True, verbose_name='Название категории')
    # slug = models.SlugField(unique=True)
    is_active = models.BooleanField('active', default=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category_order/%Y/%m/%d/',
                              default='category_order/default/placeholder_300x150.png', blank=True)

    class Meta:
        verbose_name = 'Категория заказа'
        verbose_name_plural = 'Категории заказов'

    def __str__(self):
        return f'{self.name}'

    def delete(self, using=None, keep_parents=False):
         if self.is_active == True:
             self.is_active = False
         elif self.is_active == False:
             self.is_active = True
         self.save()


class Order(models.Model):
    '''Заказ'''
    status_choice = [
        ('Active', 'Активно'),
        ('Not Active', 'Не активно')
    ]
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Компания')
    category = models.ForeignKey(CategoryOrder, on_delete=models.PROTECT, verbose_name='Категория')
    name = models.CharField(max_length=120, verbose_name='Название')
    description = models.TextField(verbose_name='Описание заказа')
    # quantity = models.IntegerField(verbose_name='Количество')
    status = models.CharField(choices=status_choice,
                              max_length=120, default='Active', verbose_name='Статус')
    create_at = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'{self.category} {self.name}, Заказ создал: {self.author}'

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)
        if self.status == 'Not Active':
            set_responses = StatusResponse.objects.filter(response_order_id=self.id)
            for response in set_responses:
                if response.status == 'On Approval':
                    response.status = 'Not Approved'
                    response.save()

    def delete(self, using=None, keep_parents=False):
         if self.status == 'Active':
             self.status = 'Not Active'
         elif self.status == 'Not Active':
             self.status = 'Active'
         self.save()


class ResponseOrder(models.Model):
    '''Отклик на заказ'''

    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    response_user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Компания')
    price = models.FloatField(default=0, verbose_name='Цена')
    offer = models.TextField(verbose_name='Предложение')
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return f'Предлжение от {self.response_user}: {self.offer}, ' \
               f'к заказу - {self.order}'

    def save(self, *args, **kwargs):
        super(ResponseOrder, self).save(*args, **kwargs)
        obj = StatusResponse.objects.create(response_order=self,
                                            status='On Approval',
                                            user_initiator=self.response_user)
        obj.save()

    

class StatusResponse(models.Model):
    '''Статус отклика для избежания UPDATE таблицы RESPONSE_ORDER'''
    status_choice = [
        ('On Approval', 'На согласовании'),
        ('Approved', 'Утвержден'),
        ('Not Approved', 'Не утвержден'),
        ('Cancelled', 'Отменен')
    ]

    response_order = models.ForeignKey(ResponseOrder, on_delete=models.CASCADE, verbose_name='Отклик на заказ')
    status = models.CharField(choices=status_choice,
                              max_length=120, verbose_name='Статус')
    time_status = models.DateTimeField(auto_now_add=True)
    user_initiator = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Пользователь инициатор')

    class Meta:
        verbose_name = 'Статус отклика'
        verbose_name_plural = 'Статусы откликов'

    def __str__(self):
        return f'У отклика с ID# {self.response_order} статус - {self.status}'

    def save(self, *args, **kwargs):
        super(StatusResponse, self).save(*args, **kwargs)
        if self.status == 'Approved':
            obj = Order.objects.get(id=self.response_order.order_id)
            obj.status = 'Not Active'
            obj.save()


class Feedback(models.Model):
    name_user = models.CharField(max_length=50, verbose_name='Имя пользователя')
    email = models.EmailField(verbose_name='Почта')
    issue = models.CharField(max_length=250, verbose_name='Тема')
    message = models.TextField(verbose_name='Сообщение')

    class Meta:
        verbose_name = 'Сообщение от пользователя'
        verbose_name_plural = 'Сообщения от пользователей'

    def __str__(self):
        return f'Сообщение от {self.name_user}'

ProductPlatform/orders/forms.py
from datetime import datetime

from django import forms
from django.forms import SelectDateWidget, DateInput

from orders.models import Order, Feedback, ResponseOrder


class CreateOrderForm(forms.ModelForm):
    """Форма для изменения данных в заказе"""

    class Meta:
        model = Order
        fields = ['category', 'name', 'description', 'end_time']
        widgets = {
            'end_time': (DateInput(attrs={'type': 'datetime-local'}))
        }

    def __init__(self, *args, **kwargs):
        super(CreateOrderForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = "Введите наименование заказа"
        self.fields['name'].widget.attrs['aria-describedby'] = "inputGroup-sizing-sm"

        self.fields['category'].widget.attrs['placeholder'] = "Выберите категорию"
        self.fields['category'].widget.attrs['aria-describedby'] = "inputGroup-sizing-sm"

        self.fields['end_time'].widget.attrs['min'] = datetime.now().strftime(
            "%Y-%m-%d %H:%M")
        self.fields['end_time'].widget.attrs['class'] = "datetimepicker"

        self.fields['description'].widget.attrs['placeholder'] = "Опишите детали заказа"


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name_user', 'email', 'issue', 'message', ]

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.fields['name_user'].widget.attrs['type'] = 'text'
        self.fields['name_user'].widget.attrs['id'] = 'name'
        self.fields['name_user'].widget.attrs['name'] = 'name'
        self.fields['name_user'].widget.attrs['placeholder'] = 'Имя...'
        self.fields['name_user'].widget.attrs['required'] = ''

        self.fields['email'].widget.attrs['type'] = 'text'
        self.fields['email'].widget.attrs['id'] = 'email'
        self.fields['email'].widget.attrs['name'] = 'email'
        self.fields['email'].widget.attrs['placeholder'] = 'Эл. почта...'
        self.fields['email'].widget.attrs['required'] = ''
        self.fields['email'].widget.attrs['pattern'] = '[^ @]*@[^ @]*'

        self.fields['issue'].widget.attrs['type'] = 'text'
        self.fields['issue'].widget.attrs['id'] = 'subject'
        self.fields['issue'].widget.attrs['name'] = 'subject'
        self.fields['issue'].widget.attrs['placeholder'] = 'Тема...'
        self.fields['issue'].widget.attrs['required'] = ''

        self.fields['message'].widget.attrs['name'] = 'user_message'
        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['id'] = 'user_message'
        self.fields['message'].widget.attrs['placeholder'] = 'Сообщение...'
        self.fields['message'].widget.attrs['required'] = ''


class ResponseOrderForm(forms.ModelForm):
    class Meta:
        model = ResponseOrder
        fields = ['price', 'offer']

    def __init__(self, *args, **kwargs):
        super(ResponseOrderForm, self).__init__(*args, **kwargs)
        self.fields['price'].widget.attrs['type'] = 'number'
        self.fields['price'].widget.attrs['min'] = '1'
        self.fields['price'].widget.attrs['step'] = '1'
        self.fields['price'].widget.attrs['id'] = 'price-suggestion'
        self.fields['price'].widget.attrs['placeholder'] = 'Предложение...'
        self.fields['price'].widget.attrs['required'] = 'True'
        self.fields['price'].widget.attrs['name'] = 'name'

        self.fields['offer'].widget.attrs['type'] = 'text'
        self.fields['offer'].widget.attrs['id'] = 'description'
        self.fields['offer'].widget.attrs['placeholder'] = 'Описание...'
        self.fields['offer'].widget.attrs['required'] = 'True'
        self.fields['offer'].widget.attrs['name'] = 'message'
        self.fields['offer'].widget.attrs['class'] = 'form-control'

ProductPlatform/orders/templates/orders/categories.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <section class="heading-page header-text" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Категории</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="meetings-page" id="meetings">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row cat-center">
                                {% if not user.role == 'Supplier' and not user.role == 'Customer' %}
                                    <div class="col-lg-12 categories-filter">
                                        <form class="categories-filter-form" id="categories_filter_form" method="GET">
                                            <div class="filter-fields left-fields">
                                                {{ filtered_categories.form }}
                                            </div>
                                        </form>
                                    </div>
                                {% endif %}
                                {% if user.role == 'Supplier' or user.role == 'Customer' %}
                                    {% for category in page_obj_active %}
                                        <div class="col-lg-4 cat-cont templatemo-item-col all soon">
                                            <div class="meeting-item cat-cont">
                                                <a class="cat-cont-a" href="{% url 'orders:category' category.id %}">
                                                    <div class="thumb">
                                                        <div class="price">
                                                            <span>Кол-во поставщиков: {{ category.count_orders }}</span>
                                                            <!-- Надо будет ещё количество добавить, но после того как это вьюху добавят -->
                                                        </div>
                                                        {% if category.image %}
                                                            <!--                                                        <img src="{{ category.image }}" alt="">-->
                                                            <img src="/media/{{ category.image }}" alt="">
                                                        {% else %}
                                                            <img src="{% static 'assets/images/placeholder_300x150.png' %}"
                                                                 alt="">
                                                        {% endif %}
                                                    </div>
                                                    <div class="down-content">
                                                        <h4>{{ category.name }}</h4>
                                                        <p>{{ category.description }}</p>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    {% for category in page_obj %}
                                        <div class="col-lg-4 cat-cont templatemo-item-col all soon">
                                            <div class="meeting-item cat-cont">
                                                <a class="cat-cont-a" href="{% url 'orders:category' category.id %}">
                                                    <div class="thumb">
                                                        <div class="price amount_suppliers">
                                                            <span>Кол-во поставщиков: {{ category.count_orders }}</span>
                                                            <!-- Надо будет ещё количество добавить, но после того как это вьюху добавят -->
                                                        </div>
                                                        {% if category.image %}
                                                            <!--                                                        <img src="{{ category.image }}" alt="">-->
                                                            <img src="/media/{{ category.image }}" alt="">
                                                        {% else %}
                                                            <img src="{% static 'assets/images/placeholder_300x150.png' %}"
                                                                 alt="">
                                                        {% endif %}
                                                    </div>
                                                    <div class="down-content">
                                                        <h4>{{ category.name }}</h4>
                                                        <p>{{ category.description }}</p>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            {#                            {% include 'includes/pagination.html' %}#}
                            {% load filter_tags %}

                            <div class="pagination col-lg-12">
                                <ul>
                                    {% if page_obj.has_previous %}
                                        <li>
                                            <a href="{% my_url 1 'page' request.GET.urlencode %}">
                                                <i class="fa fa-angle-double-left"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">
                                                <i class="fa fa-angle-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                    <li class="active">
                                        <a href="#">
                                            {{ page_obj.number }}
                                        </a>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li>
                                            <a href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">
                                                <i class="fa fa-angle-right"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">
                                                <i class="fa fa-angle-double-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% include 'includes/inc_footer.html' %}

    </section>
{% endblock %}

{% block morejs %}
    <script src="{% static 'assets/js/categories.js' %}"></script>
{% endblock %}

ProductPlatform/orders/templates/orders/category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <section class="meetings-page order" id="meetings">
        <div class="container">
            <div class="row order-content">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="meeting-single-item">
                                <div class="thumb">
                                    {% if category.image %}
                                        <img src="/media/{{ category.image }}" alt="">
                                    {% else %}
                                        <img src="{% static 'assets/images/placeholder_300x150.png' %}"
                                             alt="">
                                    {% endif %}
                                    <div class="price">
                                        <span>Кол-во поставщиков: {{ category.count_orders_done }}</span>
                                    </div>
                                </div>
                                <div class="down-content">
                                    <h4>{{ category.name }}</h4>
                                    <p class="description">
                                        {{ category.description }}
                                    </p>
                                    <div class="row">
                                        <div class="col-lg-12 top-suppliers">
                                            <h5>Топ поставщики</h5>
                                            <table class="suppliers mt-3" id="topsuppliers">
                                                <tr class="table-headers">
                                                    <th class="supplier">Поставщик</th>
                                                    <th class="orders_amount">Количество выполненных заказов</th>
                                                </tr>
                                                <!-- Топ 5 поставщиков -->
                                                {% for supplier, total in top_suppliers.items %}
                                                    <tr class="t-row">
                                                        <td>
                                                            <a href="{% url 'users:profile' supplier.id %}">
                                                                {{ supplier.comp_name }}
                                                            </a>
                                                        </td>
                                                        <td>{{ total }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </table>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="share col-lg-12">
                                                <div>
                                                    <p><span>Всего Заказов:</span> {{ all_orders_amount }}</p>
                                                </div>
                                                <div>
                                                    <p><span>Выполненные Заказы:</span> {{ all_completed_orders }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">

                        <div class="main-button-red">
                            {% if not user.role == 'Supplier' %}
                                <a class="button-green"
                                   href="{% url 'orders:create_order' %}?category_id={{ category.id }}">
                                    Создать заказ
                                </a>
                            {% endif %}
                            {% if not user.role == 'Supplier' and not user.role == 'Customer' %}
                                {#                                <a class="button-red" href="{% url 'orders:categories' %}">Назад к списку категорий</a>#}
                                <a class="{% if category.is_active == True %}close-btn{% else %}accept-btn{% endif %}"
                                   href="#"
                                   data-bs-toggle="modal"
                                   data-bs-target="#staticBackdrop">
                                    {% if category.is_active == True %}
                                        Деактивировать
                                    {% else %}
                                        Активировать
                                    {% endif %}
                                </a>

                                </div>
                                <form method="POST" action="{% url 'orders:delete_category' category.id %}">
                                    {% csrf_token %}
                                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static"
                                         data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                                         aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="staticBackdropLabel">Подтверждение
                                                        действий</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Вы действительно уверены, что хотите
                                                        {% if category.is_active == True %}
                                                            Деактивировать{% else %}Активировать{% endif %}?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="submit"
                                                            class="modal-btn {% if category.is_active == True %}close-btn{% else %}accept-btn{% endif %}">
                                                        Подтверждаю
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            {% endif %}
                        <div class="main-button-red">
                            <a class="button-red" href="{% url 'orders:categories' %}">Назад к списку категорий</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% include 'includes/inc_footer.html' %}

    </section>
{% endblock %}

{% block morejs %}
    <script src="{% static 'assets/js/table.js' %}"></script>
{% endblock %}

ProductPlatform/orders/templates/orders/delete_category.html
<form method="post">{% csrf_token %}



<p>Вы точно хотите {% if object.is_active == True %} деактивировать {% else %} активировать {% endif %} "{{ object }}"?</p>



    <input type="submit" value="Confirm">
</form>

ProductPlatform/orders/templates/orders/order_board.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <section class="orders-table-board" style="height: 100%">
        <div class="col-lg-12">
            <div class="section-heading">
                <h2>Доска Заказов</h2>
            </div>
        </div>
        <div class="container content-table">
            <div class="row row-table">
                <div class="col-12 center">
                    <form class="filter-form" method="GET">
                        <div class="filter-fields left-fields">
                            <label for="id_category">Категория:</label>
                            {{ filtered_table.form.category }}
                            <label for="id_ordering_category">Сортировка по продукту:</label>
                            {{ filtered_table.form.ordering_category }}
                        </div>
                        <div class="filter-fields">
                            <label for="search">Поиск</label>
                            {{ filtered_table.form.name }}

                            <button type="submit" class="filter-btn">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="col-12">

                    {% if page_obj %}
                        <!-- Вставляем таблицу -->
                        {% include "orders/table_order_board.html" %}
                    {% else %}
                        <h4 class="no-orders text-lg-center text-white">Увы, заказы по данному запросу не найдены.</h4>
                    {% endif %}
                </div>
            </div>
        </div>

        {% include 'includes/inc_footer.html' %}

    </section>
{% endblock %}

{% block morejs %}
    <script>
        $(document).ready(function ($) {
            $('.meeting-table-cell').click(function () {
                window.document.location = $(this).data('href');
            });
            $('.change-status').click(function () {
                window.document.location = $(this).data('href');
            });
        });
    </script>
    <script src="{% static 'assets/js/table_order.js' %}"></script>
{% endblock %}