ProductPlatform/ProductPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from ProductPlatform.script.change_order_status import start_thread_check_order_status
from orders.views import MainView

start_thread_check_order_status()  # запуск скрипта проверки заказов на актуальность по дате

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProductPlatform/orders/urls.py
from django.contrib import admin
from django.urls import path
from .views import Category, CreateOrder, OrderView, table_order, DeleteCategory, categories, DeleteOrder,UpdateOrder, DeleteResponse, UpdateResponse

app_name = 'orders'

urlpatterns = [
    path('categories/', categories, name='categories'),
    path('category/<int:id>', Category.as_view(), name='category'),
    path('create_order/', CreateOrder.as_view(), name='create_order'),
    path('view_order/<int:pk>/', OrderView.as_view(), name='view_order'),
    path("table_order/", table_order, name="table_order"),
    path('category/delete/<int:pk>/', DeleteCategory.as_view(), name='delete_category'),
    path('order_delete/<int:pk>/', DeleteOrder.as_view(), name='delete_order'),
    path('update/<int:pk>/', UpdateOrder.as_view(), name='update_order'),
    path('response_delete/<int:pk>/',
         DeleteResponse.as_view(), name='delete_response'),
    path('response_update/<int:pk>/',
         UpdateResponse.as_view(), name='response_update'),
    path('order_confirmation/<int:response_pk>/<int:order_pk>/', OrderView.order_confirmation,
         name='order_confirmation'),
    path('order_rejection/<int:response_pk>/<int:order_pk>/',
         OrderView.order_rejection, name='order_rejection'),
    


]

ProductPlatform/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import LoginListView, RegisterListView, Logout, PersonalActiveOrdersView, PersonalHistoryOrdersView, \
    ProfilePasswordResetView, ProfilePasswordResetDoneView, ProfilePasswordResetCompleteView, \
    ProfilePasswordResetConfirmView

from users.views import PersonalAccountListView, PersonalAccountEditView, ProfileView

app_name = 'users'

urlpatterns = [
    path('account/', PersonalAccountListView.as_view(), name='account'),
    path('account_edit/', PersonalAccountEditView.as_view(), name='account_edit'),
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('account_history_orders/', PersonalHistoryOrdersView.as_view(), name='account_history_orders'),
    path('account_history_orders/<int:page>/', PersonalHistoryOrdersView.as_view(), name='history_orders_page'),
    path('account_active_orders/', PersonalActiveOrdersView.as_view(), name='account_active_orders'),
    path('password-reset/', ProfilePasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', ProfilePasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ProfilePasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', ProfilePasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
]

ProductPlatform/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import Profile


class PersonalAccountEditForm(forms.ModelForm):
    """Форма для изменения данных в личном кабинете"""
    class Meta:
        model = Profile
        fields = ['username', 'first_name', 'last_name', 'email',
                  'comp_name', 'city', 'ogrn', 'phone_number',
                  'date_joined', 'bio']

    def __init__(self, *args, **kwargs):
        super(PersonalAccountEditForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['ogrn'].widget.attrs['readonly'] = True
        self.fields['comp_name'].widget.attrs['readonly'] = True
        self.fields['date_joined'].widget.attrs['readonly'] = True

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = Profile
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = "Введите имя пользователя"
        self.fields['password'].widget.attrs['placeholder'] = "Введите пароль"
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = Profile
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2', 'city', 'ogrn', 'comp_name', 'role', 'phone_number', 'bio')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = "Введите Никнейм"
        self.fields['email'].widget.attrs['placeholder'] = "Введите почту"
        self.fields['first_name'].widget.attrs['placeholder'] = "Введите Имя"
        self.fields['last_name'].widget.attrs['placeholder'] = "Введите Фамилию"
        self.fields['password1'].widget.attrs['placeholder'] = "Введите пароль"
        self.fields['password2'].widget.attrs['placeholder'] = "Подтвердите пароль"
        self.fields['city'].widget.attrs['placeholder'] = "Город"
        self.fields['city'].widget.attrs['readonly'] = "readonly"
        self.fields['ogrn'].widget.attrs['placeholder'] = "ОГРН или ЕГРИП"
        self.fields['comp_name'].widget.attrs['placeholder'] = "Название компании"
        self.fields['comp_name'].widget.attrs['readonly'] = "readonly"
        self.fields['role'].widget.attrs['placeholder'] = "Заказчик/Поставщик"
        self.fields['phone_number'].widget.attrs['placeholder'] = "Контактный телефон"
        self.fields['bio'].widget.attrs['placeholder'] = "Описание"

        for field_name, field in self.fields.items():
            if field_name != 'role':
                field.widget.attrs['class'] = 'form-control py-2'
            else:
                field.widget.attrs['class'] = 'form-select py-2'

ProductPlatform/users/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView
from django.views.generic.edit import FormView

from orders.models import ResponseOrder, Order, StatusResponse
from users.forms import PersonalAccountEditForm
from users.forms import UserLoginForm, UserRegisterForm
from users.models import Profile


class PersonalAccountListView(LoginRequiredMixin, ListView):
    """Класс-обработчик для отображения информации в личном кабинете"""
    title = 'Личный кабинет'
    model = Profile
    template_name = 'users/personal_account.html'
    context_object_name = 'account'

    def get_context_data(self, *, object_list=None, **kwargs):
        """Метод для создания необходимого контекста для личного кабинета"""
        context = super(PersonalAccountListView,
                        self).get_context_data(**kwargs)
        context['account'] = Profile.objects.get(pk=self.request.user.pk)
        context['title'] = self.title
        return context


class PersonalAccountEditView(LoginRequiredMixin, UpdateView):
    """Класс-обработчик для редактирования информации в личном кабинете"""
    model = Profile
    template_name = 'users/personal_account_edit.html'
    form_class = PersonalAccountEditForm
    success_url = reverse_lazy('users:account_edit')

    def get_object(self, queryset=None):
        """Метод для получения объекта для использования"""
        return get_object_or_404(Profile, pk=self.request.user.pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """Метод для создания необходимого контекста для личного кабинета"""
        context = super(PersonalAccountEditView,
                        self).get_context_data(**kwargs)
        context['user'] = Profile.objects.get(pk=self.request.user.pk)
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, instance=self.request.user)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return redirect(self.success_url)


class LoginListView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Авторизация'


class RegisterListView(FormView):
    model = Profile
    template_name = 'users/registration.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    title = 'Регистрация'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)


class Logout(LogoutView):
    template_name = 'orders/main.html'

    def get(self, request, *args, **kwargs):
        return redirect(reverse_lazy('main'))


class PersonalActiveOrdersView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Order
    template_name = 'users/account_active_orders.html'
    context_object_name = 'orders'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        """Метод для создания необходимого контекста для активных заказов личного кабинета"""
        context = super().get_context_data(**kwargs)
        user = self.request.user
        page = self.request.GET.get('page')
        
        # для Заказчика
        if user.role == 'Customer':
            response_for_customer = ResponseOrder.objects.filter(order__author=user.pk)
            active_orders = Order.objects.select_related()\
                .filter(end_time__gte=datetime.today(), author_id=user.pk)\
                .annotate(count_response=Count('responseorder')) \
                .values('id', 'category__name', 'author__city', 'name', 'description',
                        'status', 'create_at', 'end_time', 'count_response')

            paginator = Paginator(active_orders, per_page=3)
            try:
                orders_paginator = paginator.page(page)
            except PageNotAnInteger:
                orders_paginator = paginator.page(1)
            except EmptyPage:
                orders_paginator = paginator.page(paginator.num_pages)
            context['paginator'] = orders_paginator.paginator
            context['page_obj'] = orders_paginator
            context['responses_to_orders'] = response_for_customer

            return context

        # для поставщика
        elif user.role == 'Supplier':
            active_responses = []
            responses = ResponseOrder.objects.filter(response_user=user, order__end_time__gte=datetime.today())

            for response in responses:
                statuses = StatusResponse.objects.filter(
                    response_order=response,
                    status__in=['Not Approved', 'Cancelled'])
                if len(statuses) == 0:
                    if StatusResponse.objects.filter(response_order=response, status='Approved').first():
                        active_responses.append({'response': response, 'status': 'Утверждён'})
                    else:
                        active_responses.append({'response': response, 'status': 'На утверждении'})
            
            paginator = Paginator(active_responses, per_page=3)
            try:
                orders_paginator = paginator.page(page)
            except PageNotAnInteger:
                orders_paginator = paginator.page(1)
            except EmptyPage:
                orders_paginator = paginator.page(paginator.num_pages)
            context['paginator'] = orders_paginator.paginator
            context['page_obj'] = orders_paginator
            
            return context

    def test_func(self):
        return not self.request.user.is_superuser and not self.request.user.is_staff


class PersonalHistoryOrdersView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Order
    template_name = 'users/account_history_orders.html'
    context_object_name = 'orders'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        """Метод для создания необходимого контекста для истории заказов личного кабинета"""
        context = super(PersonalHistoryOrdersView,
                        self).get_context_data(**kwargs)
        current_profile = Profile.objects.get(pk=self.request.user.pk)
        responses, orders, status_responses = None, None, None
        if current_profile.role == 'Customer':
            responses = ResponseOrder.objects.filter(order__author=self.request.user.pk, order__status='Not Active')
            orders = Order.objects.filter(author=self.request.user.pk, status='Not Active')
            status_responses = StatusResponse.objects.filter(response_order__order__author=self.request.user.pk,
                                                             response_order__order__status='Not Active')
        elif current_profile.role == 'Supplier':
            orders = Order.objects.filter(responseorder__response_user=self.request.user.pk, status='Not Active')
            responses = ResponseOrder.objects.filter(order__id__in=orders.values_list('id'), order__status='Not Active')
            status_responses = StatusResponse.objects.filter(response_order__order__id__in=orders.values_list('id'),
                                                             response_order__order__status='Not Active')
        history_orders = []
        for item in orders:
            response_count = responses.filter(order=item.id).count()
            approved_response_user_id = None
            try:
                approved_response = status_responses.get(status='Approved', response_order__order=item.id)
                if current_profile.role == 'Supplier' \
                        and approved_response.response_order.response_user.id == current_profile.id:
                    status = 'Ваш отклик утвержден'
                else:
                    status = 'Поставщик утвержден'
                approved_response_user_id = approved_response.response_order
            except Exception:
                status = 'Отменен'
            history_orders.append({
                'name': item.name,
                'author': item.author,
                'order_num': item.id,
                'description': item.description,
                'category': item.category.name,
                'city': item.author.city,
                'date_to': item.end_time.date(),
                'response_count': response_count,
                'status': status,
                'response_approved': approved_response_user_id
            })
        page = self.request.GET.get('page')
        paginator = Paginator(history_orders, per_page=3)
        try:
            orders_paginator = paginator.page(page)
        except PageNotAnInteger:
            orders_paginator = paginator.page(1)
        except EmptyPage:
            orders_paginator = paginator.page(paginator.num_pages)
        context['paginator'] = orders_paginator.paginator
        context['page_obj'] = orders_paginator
        context['user'] = current_profile
        return context

    def test_func(self):
        return not self.request.user.is_superuser and not self.request.user.is_staff


class ProfilePasswordResetView(PasswordResetView):
    title = "Сброс пароля"
    subject_template_name = "users/registration/password_reset_subject.txt"
    email_template_name = "users/registration/password_reset_email.html"
    template_name = "users/registration/password_reset_form.html"

ProductPlatform/users/templates/users/account_active_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="section main-banner" id="top" data-section="section1">
        <video autoplay muted loop>
            <source src="#"/>
        </video>
        <div class="video-overlay header-text">
            <div class="container" style="padding-top:105px">
                <div class="pull-right">
                    <a href="{% url  'users:account_edit' %}" class="btn btn-danger active"
                       style="margin: 5px 5px 5px 5px; border-radius:20px"
                       role="button"
                       aria-pressed="true">
                        Личный кабинет
                    </a>
                    <a href="{% url  'users:account_history_orders' %}" class="btn btn-danger active"
                       style="margin: 5px 5px 5px 5px; border-radius:20px"
                       role="button"
                       aria-pressed="true">
                        {% if user.role == 'Supplier' %}
                            История откликов
                        {% else %}
                            История заказов
                        {% endif %}
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section id="lk">
        <div class="container" style="padding-bottom: 100px">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="card shadow-lg border-0 rounded-lg mt-5"
                         style="background-color: rgba(250, 250, 250, 0.15);color:white">
                        <div class="card-header">
                            <h2 class="text-center font-weight-light my-4 ">
                                {% if user.role == 'Supplier' %}
                                    Отклики на утверждении
                                {% else %}
                                    Активные заказы
                                {% endif %}</h2>
                        </div>
                        <div class="card-body">
                            <div class="col-md-12 mx-auto">
                                <div class="col-12">
                                    {% if not orders and not responses %}
                                        <div class="card-header" style="padding: 150px">
                                            <h4 class="text-center font-weight-light my-4 text-primary">
                                                {% if user.role == 'Supplier' %}
                                                    У Вас нет активных откликов
                                                    :-(
                                                {% else %}
                                                    У Вас нет активных заказов
                                                    :-(
                                                {% endif %}</h4>
                                        </div>
                                    {% endif %}
                                    {% if user.role == 'Customer' %}
                                        {% for order in page_obj %}
                                            <div class="card-wrapper "
                                                 style="{% if user.id == order.response_approved.response_user.id %}background:#931c1c;{% else %}background:rgba(250, 250, 250, 0.15);{% endif %}margin-bottom:2rem; padding:2rem; border-radius:20px">
                                                <div class="top-line row">
                                                    <div class="col">
                                                        <a class="card-title"
                                                           href="{% url 'orders:view_order' order.id %}"><strong>Заказ
                                                            №{{ order.id }} | {{ order.name }}</strong></a>
                                                    </div>
                                                    <div class="col-auto">
                                                        <p class="price mbr-fonts-style display-7 text-white">
                                                            Статус: <strong>{% if order.status == 'Active' %}Поиск
                                                            поставщика{% else %}Поставщик утверждён{% endif %}</strong>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="bottom-line">
                                                    <p class="mbr-text mbr-fonts-style display-7 text-white">
                                                        <strong>Категория</strong>:
                                                        {{ order.category__name }}<br><strong>Адрес</strong>:
                                                        г. {{ order.author__city }}<br><strong>Описание</strong>:
                                                        {{ order.description }}<br><strong>Срок</strong>: до
                                                        {{ order.end_time }}<br><strong>
                                                        Цена</strong>:&nbsp;{% if order.response_approved %}
                                                        {{ order.response_approved.offer }} {% else %}
                                                        договорная {% endif %}
                                                    </p>
                                                </div>
                                                <div class="top-line row">
                                                    <div class="col">

                                                        {% if order.count_response > 0 %}
                                                            <strong>Предложения:</strong><br>
                                                            {% for response in responses_to_orders %}
                                                                {% if response.order_id == order.id %}
                                                                    <a href="{% url 'users:profile' response.response_user.id %}"
                                                                       class="card-title mbr-fonts-style display-7">
                                                                        {{ response.response_user.comp_name }}
                                                                        - {{ response.price|floatformat:2 }} ₽
                                                                    </a>
                                                                    <br>
                                                                {% endif %}
                                                            {% endfor %}
                                                        {% endif %}
                                                    </div>
                                                    <div class="col-auto">
                                                        <p class="price mbr-fonts-style display-7 text-white">
                                                            Откликов: <strong> {{ order.count_response }}</strong>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% elif user.role == 'Supplier' %}
                                        {% for response in page_obj %}
                                            <div class="card-wrapper "
                                                 style="{% if user.id == order.response_approved.response_user.id %}background:#931c1c;{% else %}background:rgba(250, 250, 250, 0.15);{% endif %}margin-bottom:2rem; padding:2rem; border-radius:20px">
                                                <div class="top-line row">
                                                    <div class="col">
                                                        <a class="card-title"
                                                           href="{% url 'orders:view_order' response.response.order.id %}">
                                                            <strong>
                                                                Отклик №{{ response.response.id }}
                                                            </strong>
                                                        </a>
                                                    </div>
                                                    <div class="col-auto">
                                                        <p class="price mbr-fonts-style display-7 text-white">
                                                            Статус: <strong>{{ response.status }}</strong></p>
                                                    </div>
                                                </div>
                                                <div class="bottom-line">
                                                    <p class="mbr-text mbr-fonts-style display-7 text-white">
                                                        <strong>Категория</strong>:
                                                        {{ response.response.order.category }}<br><strong>Цена</strong>:
                                                        {{ response.response.price|floatformat:2 }} ₽<br><strong>Оффер</strong>:
                                                        {{ response.response.offer }}<br>
                                                    </p>
                                                </div>
                                                <div class="top-line row">
                                                    <div class="col">
{#                                                        <strong>Заказ:</strong><br>#}
{#                                                        <a href="#"#}
{#                                                           class="card-title mbr-fonts-style display-7">#}
{#                                                            {{ response.order__name }}</a><br>#}
{#                                                        </a>#}
                                                    </div>
                                                    <div class="col-auto">
                                                        <p class="price mbr-fonts-style display-7 text-white">
                                                            <a href="{% url 'orders:view_order' response.response.order_id %}"
                                                               class="card-title mbr-fonts-style display-7">
                                                                <strong>Заказ
                                                                    № {{ response.response.order_id }}:</strong> {{ response.response.order.name }}
                                                            </a><br>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                {% include 'includes/pagination.html' %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% include 'includes/inc_footer.html' %}

    </section>
{% endblock %}

ProductPlatform/users/templates/users/login.html
{% extends 'users/login_reg_base.html' %}

{% block errors %}
    {% if form.errors %}
        <div
                id="error-list"
                class="alert fade show"
                role="alert"
                style="margin-top: 50px; display: flex;"
        >
            <div>
                {{ form.non_field_errors }}
                {% for error in form %}
                    {{ error.errors }}
                {% endfor %}
            </div>
            <button
                    id="close-btn"
                    type="button"
                    class="close"
                    data-dismiss="alert"
                    aria-label="Close"
            >
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <form action="{% url 'users:login' %}" method="post" id="contact">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-12">
                <h2>Авторизация</h2>
            </div>
            <div class="col-lg-12 inp">
                <fieldset>
                    <label class="small mb-1" for="inputEmailAddress">Имя пользователя</label>
                    {{ form.username }}
                </fieldset>
            </div>
            <div class="col-lg-12 inp">
                <fieldset>
                    <label class="small mb-1" for="inputPassword">Пароль</label>
                    {{ form.password }}
                </fieldset>
            </div>
            <div class="col-lg-12 submit-btn">
                <fieldset class="col-lg-12 submit-btn-login">
                    <a class="small" href="{% url "users:password_reset" %}">Забыли пароль?</a>
                    <button class="button button-login-reg"
                            id='register_button'
                            type="submit">
                        Авторизоваться
                    </button>
                </fieldset>
            </div>
        </div>
        <div class="footer">
            <p><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></p>
        </div>
    </form>
{% endblock %}